package hublist

import (
	"context"
	"os"
	"os/exec"
	"sort"
	"testing"
	"unicode"
)

func TestTEGenerate(t *testing.T) {
	if os.Getenv("CODEGEN") != "true" {
		t.SkipNow()
	}
	var resp struct {
		Columns map[string]string `json:"columns"`
	}
	err := teGetRaw(context.Background(), TELists[0], &resp)
	if err != nil {
		t.Fatal(err)
	} else if len(resp.Columns) < 20 {
		t.Fatalf("%d columns", len(resp.Columns))
	}
	var cols [][2]string
	for name, typ := range resp.Columns {
		cols = append(cols, [2]string{name, typ})
	}
	sort.Slice(cols, func(i, j int) bool {
		return cols[i][0] < cols[j][0]
	})
	const fname = "te_home_gen.go"
	f, err := os.Create(fname)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	f.WriteString("// Code generated by te_core_test.go. DO NOT EDIT.\n\n")
	f.WriteString("package hublist\n\n")
	f.WriteString("type teHub struct{\n")
	for _, col := range cols {
		name := col[0]
		name = string(unicode.ToUpper(rune(name[0]))) + name[1:]
		f.WriteString("\t" + name + " ")
		switch col[1] {
		case "number":
			f.WriteString("int")
		case "string":
			f.WriteString("string")
		default:
			f.WriteString("interface{}")
		}
		f.WriteString(" `json:\"" + col[0] + "\"`\n")
	}
	f.WriteString("}\n")
	err = exec.Command("go", "fmt", fname).Run()
	if err != nil {
		t.Fatal(err)
	}
}
