// Code generated by te_core_test.go. DO NOT EDIT.

package hublist

type teHub struct {
	Address     string  `json:"address"`
	Bots        int     `json:"bots"`
	Country     string  `json:"country"`
	Description string  `json:"description"`
	Email       string  `json:"email"`
	Encoding    string  `json:"encoding"`
	Failover    string  `json:"failover"`
	Icon        string  `json:"icon"`
	Infected    int     `json:"infected"`
	Logo        string  `json:"logo"`
	Maxhubs     int     `json:"maxhubs"`
	Maxusers    int     `json:"maxusers"`
	Minshare    int     `json:"minshare"`
	Minslots    int     `json:"minslots"`
	Name        string  `json:"name"`
	Network     string  `json:"network"`
	Operators   int     `json:"operators"`
	Rating      int     `json:"rating"`
	Reliability float64 `json:"reliability"`
	Shared      int     `json:"shared"`
	Software    string  `json:"software"`
	Status      string  `json:"status"`
	Users       int     `json:"users"`
	Website     string  `json:"website"`
}
